#!/bin/bash

PK=${PK:-/var/log/packages}

AZ=${AZ:-\\033[1;34m}
VD=${VD:-\\033[1;32m}
AM=${AM:-\\033[1;33m}
VM=${VM:-\\033[1;2;31m}
BR=${BR:-\\033[1;37m}
RS=${RS:-\\033[0m}

existcheck(){
	[[   `slapt-get -search $X` ]] && echo -e "$AM $X $BR -->$AM Instalável$RS"
	[[ ! `slapt-get -search $X` ]] && echo -e "$VM $X $RS"
}

for X in `cat $1`; do
	A=0
	[[ $X = 0 ]] || [[ `echo $X | grep '#'` ]] && A=1
	[[ `echo $X | grep '!'` ]] && echo -e "$AZ\n $( echo $X | cut -c 2- | sed 's/_/ /g' ) \n$RS" && A=1
	[[ $A = 0 ]] && [[ `ls $PK | grep -w -i ^$X` ]] && echo -e "$VD $X $BR --> $VD $( ls $PK | grep -i ^$X | head -1 ) $RS"
	[[ $A = 0 ]] && [[ ! `ls $PK | grep -w -i ^$X` ]] && existcheck
done

exit 0
