#!/bin/sh

REX=~/Binary/Rex
OUTPUT_DIR="$PWD/_output"
CWD="$(pwd)"

TMPDIR="$(mktemp -d)"
cd "$TMPDIR" || exit 1

[ "$1" != "" ] && PKG_VERSION="$1"

set -e

apk add glslang glm glm-dev libffi-dev libxkbcommon-dev expat-dev libxcb-dev vulkan-headers vulkan-loader-dev vulkan-loader vulkan-tools wayland-dev wayland-protocols
git clone https://github.com/LinuxDicasPro/vulkan-smoketest.git

cd vulkan-smoketest/
mkdir -p ./build ./build-wayland
cd build

cmake .. -DCMAKE_BUILD_TYPE=Release

make -j$(nproc)
strip vulkan-smoketest

cd -
cd build-wayland

cmake .. -DBUILD_SELECTION=WAYLAND -DCMAKE_BUILD_TYPE=Release

make -j$(nproc)
strip vulkan-smoketest-wayland

cd -

mkdir -p "$OUTPUT_DIR"
mv -v build/vulkan-smoketest "$OUTPUT_DIR/vulkan-smoketest-musl"
mv -v build-wayland/vulkan-smoketest-wayland "$OUTPUT_DIR/vulkan-smoketest-wayland-musl"

cd "$CWD"
rm -rf "$TMPDIR"

echo "Binários salvos em $OUTPUT_DIR"
