#!/bin/bash

AZ=${AZ:-\\033[1;34m}
VD=${VD:-\\033[1;32m}
AM=${AM:-\\033[1;33m}
VM=${VM:-\\033[1;2;31m}
BR=${BR:-\\033[1;37m}
RS=${RS:-\\033[0m}

NL=${NL:-/dev/null}
TM=${TM:-temp}

rm FORINSTALL NOREPO 2> $NL
mkdir $TM 2> $NL

apt list -i 2> $NL | sed -e 's| \[.*\]||g' -e 's|/.*now |_|g' -e 's| |_|g' -e '1d' 1> $TM/LST1
apt list 2> $NL 1> $TM/LST2

existcheck(){
    CK=0
	[[ `apt-cache search $X | grep ^$X` ]] && echo -e "$AM $X $BR-->$AM $(cat $TM/LST2 | grep ^$X | tail -1)$RS" && echo $X >> FORINSTALL && CK=1
	[[ $CK = 0 ]] && echo -e "$VM $X $BR-->$VM $X Não Encontrado.$RS" && echo $X >> NOREPO
}

for X in `cat $1`; do
	A=0
    B=0
	[[ $X = 0 ]] || [[ `echo $X | grep '#'` ]] && A=1
	[[ `echo $X | grep '!'` ]] && echo -e "$AZ\n $( echo $X | cut -c 2- | sed 's/_/ /g' ) \n$RS" && A=1
	[[ $A = 0 ]] && [[ `dpkg --get-selections | grep ^$X` ]] && echo -e "$VD $X $BR-->$VD $(cat $TM/LST1 | grep ^$X | tail -1)$RS" && B=1
	[[ $A = 0 ]] && [[ $B = 0 ]] && existcheck
done

rm -r $TM

exit 0
