#!/bin/bash

# By Mauricio Ferrari. 28/07/2020.

# Configuração Manual
LR=$(pwd)/Mint20
SL="/etc/apt/sources.list.d"

officialrepo(){
	echo 'deb http://mint-packages.c3sl.ufpr.br ulyana main upstream import backport 
deb http://mirror.ufscar.br/ubuntu focal main restricted universe multiverse
deb http://mirror.ufscar.br/ubuntu focal-updates main restricted universe multiverse
deb http://mirror.ufscar.br/ubuntu focal-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb http://archive.canonical.com/ubuntu/ focal partner' | tee $SL/official-package-repositories.list

<< EOF1

	echo 'deb http://mint-packages.c3sl.ufpr.br ulyana main upstream import backport 
deb-src http://mirror.ufscar.br/ubuntu focal main restricted universe multiverse
deb-src http://mirror.ufscar.br/ubuntu focal-updates main restricted universe multiverse
deb-src http://mirror.ufscar.br/ubuntu focal-backports main restricted universe multiverse
deb-src http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://archive.canonical.com/ubuntu/ focal partner' | tee $SL/official-source-repositories.list

EOF1

}

flaconrepo(){
	wget -q http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/Release.key -O- | apt-key add -
	echo 'deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./' | tee $SL/flacon.list
}

nulloyrepo(){
	wget -q http://download.opensuse.org/repositories/multimedia:/apps:/nulloy/Debian_9.0/Release.key -O- | apt-key add -
	echo 'deb http://download.opensuse.org/repositories/multimedia:/apps:/nulloy/Debian_9.0/ /' | tee $SL/nulloy.list
}

googlerepo(){
	wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O- | apt-key add - 
	echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main' | tee $SL/google.list
}

spotifyrepo(){
	apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
	echo 'deb http://repository.spotify.com stable non-free' | tee $SL/spotify.list
}

skyperepo(){
	dpkg -s apt-transport-https > /dev/null || bash -c "apt-get update; apt-get install apt-transport-https -y"
	echo 'deb [arch=amd64] https://repo.skype.com/deb stable main' | tee $SL/skype.list
}

extrarepo(){
	add-apt-repository ppa:lumas/photoqt
	add-apt-repository ppa:gezakovacs/ppa
	add-apt-repository ppa:ytvwld/asciiquarium
	add-apt-repository ppa:lightzone-team/lightzone
}

stretchrepo(){
	echo 'deb http://www.deb-multimedia.org stretch main
	deb http://deb.debian.org/debian/ stretch main contrib non-free' | tee $SL/debian.list
	apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
	http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
	dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
}

stretchrepodisable(){
	mv $SL/debian.list $SL/debian.list.bak && apt update
}

localrepo(){
	[[ $LR != "" ]] && dpkg -i $LR/*.deb && dpkg --configure -a
}

upgradesystem(){
	officialrepo && apt-get update && apt-get upgrade
}

installextra(){
	flaconrepo; nulloyrepo; googlerepo; spotifyrepo; skyperepo; extrarepo #; stretchrepo
	apt-get update
	apt-get install -y asciiquarium dvdrip flacon dosemu google-chrome-stable google-earth-pro-stable leafpad lightzone nulloy nulloy-gstreamer nulloy-taglib photoqt skypeforlinux spotify-client transmageddon
	#stretchrepodisable
}

firefox(){
	apt-get install -y firefox firefox-locale-pt
}

download(){
	apt-get install -y qbittorrent transmission-gtk uget aria2
}

social(){
	apt-get install -y telegram-desktop whatsapp-desktop
}

audio(){
	apt-get install -y audacious clementine
}

multimedia(){
	apt-get install -y dragonplayer mpv smplayer vlc
}

rip(){
	apt-get install -y asunder acidrip ripperx sound-juicer
}

audioedit(){
	apt-get install -y ardour audacity converseen easytag kwave
}

transcode(){
	apt-get install -y handbrake winff
}

screen(){
	apt-get install -y flameshot kazam obs-studio peek recordmydesktop screenkey simplescreenrecorder vokoscreen-ng
}

burn(){
	apt-get install -y brasero k3b xfburn
}

iso(){
	apt-get install -y acetoneiso isomaster
}

video(){
	apt-get install -y kdenlive kino lmms openshot pitivi shotcut
}

imagem(){
	apt-get install -y darktable gimp gwenview inkscape karbon kolourpaint krita rawtherapee
}

webcam(){
	apt-get install -y cheese digikam
}

ciencia(){
	apt-get install -y gcu-bin geogebra kalzium kmplot kstars logisim marble oregano stellarium umbrello xoscope
}

zipfm(){
	wget https://github.com/MauricioFerrari-NovaTrento/repo-mint20/raw/master/p7zip-desktop/p7zip-desktop_16.02+mint20-1_amd64.deb ~/
	apt-get install -y ~/p7zip-desktop_16-02+mint20-1_amd64.deb
}

zip(){
	apt-get install -y p7zip p7zip-full p7zip-rar; zipfm
}

develop(){
	apt-get install -y anjuta build-essential cmake codeblocks geany lazarus netbeans spyder sublime-text sweethome3d
}

office(){
	apt-get install -y gnumeric scribus xreader
}

text(){
	apt-get install -y gedit kate xed
}

bleach(){
	wget https://download.bleachbit.org/bleachbit_4.0.0_all_ubuntu1804.deb ~/
	apt-get install -y ~/bleachbit_4.0.0_all_ubuntu1804.deb
}

clean(){
	apt-get install -y stacer sweeper; bleach
}

utilities(){
	apt-get install -y aqemu arandr cairo-dock cool-retro-term gparted redshift rxvt-unicode timeshift xterm
}

shelltools(){
	apt-get install -y dialog yad zenity
}

games(){
	apt-get install -y 0ad assaultcube dosbox gameconqueror
}

terminal(){
	apt-get install -y alien alsa-utils cabextract git mtr neofetch python3-pip testdisk usbutils  
}

extra(){
	apt-get install -y aview bb cmatrix cowsay espeak figlet oneko sl toilet fortune-mod fortunes-br libaa-bin python3-venv rtorrent
}

disableservices(){
	systemctl disable rsyslog.service
	systemctl disable lvm2-monitor.service
	systemctl disable pppd-dns.service
	systemctl disable hddtemp.service
	systemctl disable lm-sensors.service 
	systemctl disable ModemManager.service
	systemctl disable logrotate.service
	systemctl disable grub-common.service
}

remove(){
	apt-get remove -y hexchat thunderbird rhythmbox gnote onboard onboard-common fortune* vim.tiny
	apt-get autoremove -y
}

<< CMT

brmodelo easymp3gain exmplayer umplayer frostwire

qmplay2 spectacle recordmydesktop-gtk furiousisomount
natron xaralx teamviewer vscode fltk pencil eclipse libre-office only-office wps-office fslint xdialog photorec

openarena flare opensonic smc
virtualbox wine qphotorec html2pdf package-converter video-to-ascii vim

celestia gresistor flashplayer-sa-projector PacketTracer

CMT

echo && echo -e "\033[1;35m Iniciando Script Pós Instalação Linux Mint 20! \033[0m" && echo

<< EOF2

echo -e "\033[1;32m Removendo Programas Desnecessários... \033[0m"             && remove
echo -e "\033[1;33m Instalando o Repositório Local... \033[0m"                 && localrepo
echo -e "\033[1;34m Atualizando o Sistema... \033[0m"                          && upgradesystem
echo && echo -e "\033[1;35m Instalação de Programas no Linux Mint 20! \033[0m" && echo
echo -e "\033[1;37m Instalando Navegador Web... \033[0m"                       && firefox
echo -e "\033[1;36m Instalando Ferramentas de Download e Torrent... \033[0m"   && download
echo -e "\033[1;31m Instalando Programas de Comunicação ... \033[0m"           && social
echo -e "\033[1;32m Instalando Reprodutores de Áudio... \033[0m"               && audio
echo -e "\033[1;33m Instalando Reprodutores Multimídia... \033[0m"             && multimedia
echo -e "\033[1;34m Instalando Ripadores de Disco... \033[0m"                  && rip
echo -e "\033[1;35m Instalando Editores de Áudio... \033[0m"                   && audioedit
echo -e "\033[1;36m Instalando Transcodificadores... \033[0m"                  && transcode
echo -e "\033[1;31m Instalando Programas de Captura de Tela... \033[0m"        && screen
echo -e "\033[1;32m Instalando Programas de Gravação de Discos... \033[0m"     && burn
echo -e "\033[1;33m Instalando Ferramentas de ISO... \033[0m"                  && iso
echo -e "\033[1;34m Instalando Editores de Video... \033[0m"                   && video
echo -e "\033[1;35m Instalando Editores e Visualizadores de imagem... \033[0m" && imagem
echo -e "\033[1;36m Instalando Programas de WebCAM... \033[0m"                 && webcam
echo -e "\033[1;31m Instalando Programas Educativos e Científicos... \033[0m"  && ciencia
echo -e "\033[1;32m Instalando o P7ZIP Completo... \033[0m"                    && zip
echo -e "\033[1;33m Instalando Programas de Desenvolvimento... \033[0m"        && develop
echo -e "\033[1;34m Instalando Ferramentas de Escritório... \033[0m"           && office
echo -e "\033[1;35m Instalando Editores de Texto... \033[0m"                   && text
echo -e "\033[1;36m Instalando Limpadores de Sistema... \033[0m"               && clean
echo -e "\033[1;31m Instalando Utilitários... \033[0m"                         && utilities
echo -e "\033[1;32m Instalando Extras para o Shell... \033[0m"                 && shelltools
echo -e "\033[1;33m Instalando Jogos... \033[0m"                               && games
echo -e "\033[1;34m Instalando Ferramentas para Terminal... \033[0m"           && terminal
echo -e "\033[1;35m Instalando Frescuradas Extras... \033[0m"                  && extra

EOF2

echo -e "\033[1;36m Instalando Programas Adicionais... \033[0m"                && installextra

<< EOF3

echo && echo -e "\033[1;35m Ajustes Finais no Linux Mint 20! \033[0m"          && echo
echo -e "\033[1;32m Desabilitando Serviços Desnecessários... \033[0m"          && disableservices
echo -e "\033[1;32m Executando Operações Personalizadas... \033[0m"           #&& person

EOF3

echo && echo -e "\033[1;35m Script Pós Instalação do Linux Mint 20 Concluído! \033[0m" && echo

exit 0
