#!/bin/bash

# SlaptCP v1.1 - By Mauricio Ferrari - 30/08/2020.

# Configuração Manual
DR=~/Current2

# Constantes A=${A:-B}
DB=${DB:-/var/cache/slapt-get/*}
NL=${NL:-/dev/null}

# Finalização do script
fim(){
	echo -e "\033[0m" && exit 0
}

# Listando o cache dos pacotes baixados
[[ $1 = "ls" ]] || [[ $1 = "rm" ]] && [[ ! `ls -R $DB 2> $NL | grep txz` ]] && echo && echo -e "\033[1;31m Diretório $DB Vazio." && fim
[[ $1 = "ls" ]] && echo -e "\033[1;37m" && ls -R $DB | grep ".txz" && fim
[[ $1 = "rm" ]] && DR=$(echo $DB | cut -d '/' -f 1-4) && cd $DR && find -H . -type d -print0 | xargs -0 -L1 -i sudo rm -r {} 2> $NL
[[ $1 = "rm" ]] && sudo rm -r $DB.t?z 2> $NL
[[ $1 = "rm" ]] && echo -e "\n\033[1;34m Cache slapt-get redefinido." && fim

# Backup dos pacotes instalados no sistema
[[   `ls -R $DB 2> $NL | grep txz` ]] && echo -e "\033[1;34m" && find -H $DB -type f -print0 | xargs -0 -L1 -i cp -v {} $DR | cut -d "'" -f 2 | sed "s/$/ copiado/g" | grep -v package_data && rm $DR/package_data && fim
[[ ! `ls -R $DB 2> $NL | grep txz` ]] && echo && echo -e "\033[1;33m Nada Copiado." && fim

