#!/bin/bash
#
# ### ToDo v1.1 - Anotação pelo terminal - By Mauricio Ferrari - 16/01/2022 ###
#
##################################################################################

todo="$(realpath $0).txt"
[ ! -f "$todo" ] && echo > "$todo"


tla()
{
	[ "$#" -eq 0 ] && {
		echo -e "$(< "$todo")" 
	} || {
		: "$(md5sum <<< "$*")"; echo "\e[34m${_::5} \e[33m-> \e[31m$*\e[m" >> "$todo"
	}
}


tlr()
{
	[ "$1" ] && sed -i "/^[\]e\[34m$*/d" "$todo"
}


[ "${0##*/}" == "tla" ] && tla $*
[ "${0##*/}" == "tlr" ] && tlr $*
