#!/bin/bash

set -e

APPDIR=$(cd "${0%/*}" && echo $PWD)

prgname="explorer"
configdir=~/.config/mxnt
gamedir="$configdir/$prgname"
winedata="$APPDIR/winefiles"

exedir='C:\\windows'
exe='explorer.exe'

mkdir -p "$gamedir"

cd $APPDIR

# Limpar links simbólicos

find "$gamedir/dosdevices/"* -maxdepth 1 -type l -ls -delete || true
find "$gamedir/drive_c/"* -maxdepth 1 -type l -ls -delete    || true

# preparar diretório do jogo

mkdir -p $gamedir/drive_c/users/$USER/{AppData/{Local/Microsoft/Windows/{History,INetCache,INetCookies},LocalLow,Roaming/Microsoft/Windows/{Network\ Shortcuts,Printer\ Shortcuts,Recent,SendTo,Start\ Menu,Templates,Themes}},Contacts,Desktop,Documents,Downloads,Favorites,Links,Music,Pictures,Saved\ Games,Searches,Temp,Videos}

# criar links simbólicos

ln -s "/" "$gamedir/dosdevices/z:"                && echo -e "Drive z: Verificado"
ln -s "$HOME" "$gamedir/dosdevices/h:"            && echo -e "Drive h: Verificado"
ln -s "$gamedir/drive_c" "$gamedir/dosdevices/c:" && echo -e "Drive c: Verificado"
ln -s "$winedata/drive_c/"* "$gamedir/drive_c/"   && echo -e "Atalho drive_c Verificado"

# executando o programa

__GL_THREADED_OPTIMIZATIONS=1 \
__GL_SHADER_DISK_CACHE=1 \
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 \
__GL_DXVK_OPTIMIZATIONS=1 \
__GL_SHADER_DISK_CACHE_PATH="$gamedir" \
XDG_CACHE_HOME="$gamedir" \
MESA_GLTHREAD=true \
DISPLAY="$DISPLAY" \
PULSE_LATENCY_MSEC=60 \
WINE_LARGE_ADDRESS_AWARE=1 \
STAGING_SHARED_MEMORY=1 \
NTFS_MODE=0 \
WINEESYNC=1 \
WINEPREFIX="$gamedir" \
"./Wine/wine" 'C:\\windows\\system32\\start.exe' /wait /max /b /d "$exedir" "$exe"
