#!/bin/bash

set -e

APPDIR=$(cd "${0%/*}" && echo $PWD)

prgname="StreetRacingClub"
configdir=~/.config/mxnt
gamedir="$configdir/$prgname"
winedata="$APPDIR/winefiles"

exedir='C:\\Program Files (x86)/GameHitZone.com/StreetRacingClub/'
exe='StreetRacingClub.exe'

mkdir -p "$gamedir"

cd $APPDIR

# Limpar links simbólicos

find "$gamedir/dosdevices/"* -maxdepth 1 -type l -ls -delete || true
find "$gamedir/drive_c/"* -maxdepth 1 -type l -ls -delete    || true

# preparar diretório do jogo

mkdir -p $gamedir/drive_c/users/$USER/{AppData/{Local/Microsoft/Windows/{History,INetCache,INetCookies},LocalLow,Roaming/Microsoft/Windows/{Network\ Shortcuts,Printer\ Shortcuts,Recent,SendTo,Start\ Menu,Templates,Themes}},Contacts,Desktop,Documents,Downloads,Favorites,Links,Music,Pictures,Saved\ Games,Searches,Temp,Videos}

# criar links simbólicos

ln -s "/" "$gamedir/dosdevices/z:"                && echo -e "Drive z: Verificado"
ln -s "$HOME" "$gamedir/dosdevices/h:"            && echo -e "Drive h: Verificado"
ln -s "$gamedir/drive_c" "$gamedir/dosdevices/c:" && echo -e "Drive c: Verificado"
ln -s "$winedata/drive_c/"* "$gamedir/drive_c/"   && echo -e "Atalho drive_c Verificado"

test ! -e "$gamedir/.gecko" && {
    WINEPREFIX="$gamedir" "./Wine/wine" "./Wine/winedata/wine-gecko-2.47.4-x86_64.msi"
    WINEPREFIX="$gamedir" "./Wine/wine" "./Wine/winedata/wine-gecko-2.47.4-x86.msi"
    > "$gamedir/.gecko"
}

# executando o programa

VK_ICD_NVIDIA=$(ls /usr/share/vulkan/icd.d/*nvidia*.json /etc/vulkan/icd.d/*nvidia*.json | grep 'nvidia' | paste -d: -s )

__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 \
__NV_PRIME_RENDER_OFFLOAD=1 \
__GLX_VENDOR_LIBRARY_NAME=nvidia \
__VK_LAYER_NV_optimus=NVIDIA \
EGL_NV_triple_buffer=1 \
MESA_GLTHREAD=true \
VK_ICD_FILENAMES="$VK_ICD_NVIDIA" \
WINE_VK_VULKAN_ONLY=1 \
VKD3D_DEBUG=none \
VKD3D_SHADER_DEBUG=none \
__GL_THREADED_OPTIMIZATIONS=1 \
__GL_SHADER_DISK_CACHE=1 \
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 \
__GL_DXVK_OPTIMIZATIONS=1 \
__GL_SHADER_DISK_CACHE_PATH="$gamedir" \
DXVK_STATE_CACHE=0 \
DXVK_ASYNC=1 \
DXVK_LOG_LEVEL=none \
DXVK_LOG_PATH="$gamedir" \
DXVK_STATE_CACHE_PATH="$gamedir"
XDG_CACHE_HOME="$gamedir" \
MESA_GLTHREAD=true \
DISPLAY="$DISPLAY" \
PULSE_LATENCY_MSEC=60 \
WINE_LARGE_ADDRESS_AWARE=1 \
STAGING_SHARED_MEMORY=1 \
NTFS_MODE=0 \
WINEESYNC=1 \
WINEDLLOVERRIDES="winemenubuilder.exe=d;d3d10core.dll,d3d11.dll,d3d8.dll,d3d9.dll,dxgi.dll=n" \
WINEPREFIX="$gamedir" \
"./Wine/wine" 'C:\\windows\\system32\\start.exe' /wait /max /b /d "$exedir" "$exe"
