#!/bin/bash

set -e

APPDIR=$(cd "${0%/*}" && echo $PWD)

gamedir="$APPDIR/winefiles"
exedir='C:\\Program Files (x86)/GameHitZone.com/StreetRacingClub/'
exe='StreetRacingClub.exe'
cd $APPDIR

VK_ICD_NVIDIA=$(ls /usr/share/vulkan/icd.d/*nvidia*.json /etc/vulkan/icd.d/*nvidia*.json | grep 'nvidia' | paste -d: -s )

__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 \
__NV_PRIME_RENDER_OFFLOAD=1 \
__GLX_VENDOR_LIBRARY_NAME=nvidia \
__VK_LAYER_NV_optimus=NVIDIA \
EGL_NV_triple_buffer=1 \
MESA_GLTHREAD=true \
VK_ICD_FILENAMES="$VK_ICD_NVIDIA" \
WINE_VK_VULKAN_ONLY=1 \
VKD3D_DEBUG=none \
VKD3D_SHADER_DEBUG=none \
__GL_THREADED_OPTIMIZATIONS=1 \
__GL_SHADER_DISK_CACHE=1 \
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 \
__GL_DXVK_OPTIMIZATIONS=1 \
__GL_SHADER_DISK_CACHE_PATH="$gamedir" \
DXVK_STATE_CACHE=0 \
DXVK_ASYNC=1 \
DXVK_LOG_LEVEL=none \
DXVK_LOG_PATH="$gamedir" \
DXVK_STATE_CACHE_PATH="$gamedir"
XDG_CACHE_HOME="$gamedir" \
MESA_GLTHREAD=true \
DISPLAY="$DISPLAY" \
PULSE_LATENCY_MSEC=60 \
WINE_LARGE_ADDRESS_AWARE=1 \
STAGING_SHARED_MEMORY=1 \
NTFS_MODE=0 \
WINEESYNC=1 \
WINEDLLOVERRIDES="winemenubuilder.exe=d;d3d10core.dll,d3d11.dll,d3d8.dll,d3d9.dll,dxgi.dll=n" \
WINEPREFIX="$gamedir" \
"./Wine/wine" 'C:\\windows\\system32\\start.exe' /wait /max /b /d "$exedir" "$exe"
