#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=cudatoolkit
FILENAME=cuda
VERSION=11.6.0
DRIVER=510.39.01
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

SWD=$PWD

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
TMP=${TMP:-/tmp/MXNT}
PKG=$TMP/package-$PRGNAM
LINK1=https://developer.download.nvidia.com/compute/cuda/11.6.0/local_installers/cuda_11.6.0_510.39.01_linux.run
LINK2=

if [ "$ARCH" = "i586" ]; then
	SLKCFLAGS="-O2 -march=i586 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-O2 -march=i686 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "aarch64" ]; then
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX="64"
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
	LIBDIRSUFFIX="64"
else
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK1
[ "$TMP" != "/tmp" ] && rm -rf $TMP
[ "$TMP" != "/tmp/MXNT" ] && mkdir -p $TMP
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; rm -rf $PRGNAM-$VERSION
mkdir -p $PRGNAM-$VERSION
bash $CWD/$FILENAME\_$VERSION\_$DRIVER\_linux.run --target $PRGNAM-$VERSION --noexec
cd $PRGNAM-$VERSION/builds

rm -r NVIDIA*.run bin
mkdir -p ${PKG}/usr/share/cuda/extras
mv cuda_samples $PKG/usr/share/cuda/samples
cat EULA.txt > $PKG/usr/share/cuda/EULA.txt
rm EULA.txt
mv integration nsight_compute nsight_systems $PKG/usr/share/cuda
mv cuda_sanitizer_api/compute-sanitizer $PKG/usr/share/cuda/extras/compute-sanitizer
rmdir cuda_sanitizer_api
for lib in *; do
  if [[ "$lib" =~ .*"version.json".* ]]; then
    continue
  fi
  cp -r $lib/* "${PKG}/usr/share/cuda/"
done

ln -s /usr/bin/gcc "${PKG}/usr/share/cuda/bin/gcc"
ln -s /usr/bin/g++ "${PKG}/usr/share/cuda/bin/g++"

mkdir -p "${PKG}/usr/share/licenses/$PRGNAM"
ln -s /usr/share/cuda/EULA.txt "${PKG}/usr/share/licenses/$PRGNAM/EULA.txt"
ln -s /usr/share/cuda/README

cp $PKG/usr/share/cuda/EULA.txt $PKG/usr/doc/$PRGNAM-$VERSION/
cp $PKG/usr/share/cuda/README $PKG/usr/doc/$PRGNAM-$VERSION/
mv $PKG/usr/share/cuda/cublas_version.txt \
  $PKG/usr/share/cuda/CUDA*.txt \
  $PKG/usr/share/cuda/DOCS \
  $PKG/usr/doc/$PRGNAM-$VERSION

# Create soname links.
find cuda-toolkit/targets -type f -name '*.so*' ! -path '*stubs/*' -print0 | while read -rd $'\0' _lib; do
  _base=${_lib%.so.*}
  _current_soname=$(basename ${_lib%.*})
  while [[ $_current_soname != $(basename $_base) ]]; do
    ln -sf ${_lib##*/} ${PKG}/usr/share/cuda/lib64/$_current_soname
    _current_soname=${_current_soname%.*}
  done
done

install -D -m 755 "${SWD}/files/cuda.sh" "${PKG}/etc/profile.d/cuda.sh"
install -D -m 755 "${SWD}/files/cuda.csh" "${PKG}/etc/profile.d/cuda.csh"

mkdir -p "$PKG"/usr/lib64/pkgconfig
cp "${SWD}"/files/*.pc "${PKG}"/usr/lib64/pkgconfig

sed -i "/.*unsupported GNU version.*/d" "${PKG}"/usr/share/cuda/targets/x86_64-linux/include/crt/host_config.h
sed -i "/.*unsupported clang version.*/d" "${PKG}"/usr/share/cuda/targets/x86_64-linux/include/crt/host_config.h

mkdir -p $PKG/usr/lib64
mv -fn $PKG/usr/share/cuda/targets/x86_64-linux/lib/* $PKG/usr/lib64/
rm -rf $PKG/usr/share/cuda/targets/x86_64-linux/lib
cd $PKG/usr/share/cuda
ln -sf ../../lib64 lib64

mkdir -p $PKG/usr/share/applications
cp $SWD/files/*.desktop $PKG/usr/share/applications

mkdir -p $PKG/usr/include
mv -fn $PKG/usr/share/cuda/targets/x86_64-linux/include/* $PKG/usr/include/
rm -rf $PKG/usr/share/cuda/targets/x86_64-linux/include
( cd $PKG/usr/share/cuda/ ; ln -sf ../../include include )
find $PKG/usr/include -type f | xargs chmod -c 0644

(
  cd $PKG/usr/share/cuda/bin/
  ln -sf /usr/bin/gcc-11.2.0     gcc
  ln -sf /usr/bin/g++-gcc-11.2.0 g++
)

rm -rf $PKG/usr/share/cuda/targets
rm -f $PKG/usr/lib64/libOpenCL.s*

echo "           |-----handy-ruler------------------------------------------------------|
cudatoolkit: cudatoolkit (NVIDIA's parallel computing architecture)
cudatoolkit:
cudatoolkit: CUDA is NVIDIA's parallel computing architecture. It enables dramatic
cudatoolkit: increases in computing performance by harnessing the power of
cudatoolkit: the GPU.
cudatoolkit:
cudatoolkit: Homepage https://developer.nvidia.com/cuda-toolkit
cudatoolkit:
cudatoolkit:
cudatoolkit:
cudatoolkit:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
[ "$TMP" != "/tmp" ] && rm -rf $TMP

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
