#!/bin/bash
#
# tarball2appimage by LinuxDicasPro
#
####################################


destdir=~/__APPIMAGE__
test -e "../_APPIMAGE" && destdir="../_APPIMAGE" # Opcional


###########################################

arch="x86_64"
prg="Discord"
link="https://archlinux.org/packages/extra/x86_64/discord/"

###########################################


for i in {1..35}; { printf '─'; }; printf "\n"
printf "Search latest version: "


########

VERSION=${VERSION:-"$(grep -Eom1 "([0-9]+[.])+[0-9]+" <(grep "discord" <(links -dump "$link")))"}

########


printf "\033[1;32m$VERSION\033[m\n"
for i in {1..35}; { printf '─'; }; printf "\n"


test -z "$VERSION" && {
    echo "update script. version not found!"
    exit 1
}

set -e

test ! -e $destdir && mkdir -p $destdir
cd $destdir


test -e "$prg-$VERSION-$arch.AppImage" && {
    echo "appimage found!"
    exit 0
}


test ! -e "appimagetool-x86_64.AppImage" && {
    link_tool="https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
    wget -c -q --show-progress "$link_tool"
    chmod +x "appimagetool-x86_64.AppImage"
}


#########

link_prg="https://stable.dl2.discordapp.net/apps/linux/$VERSION/discord-$VERSION.tar.gz"

#########


wget -c -q --show-progress "$link_prg"
file_prg=${link_prg##*/}

cwd=$PWD

rm -rf "$prg.AppDir"
mkdir -p "$prg.AppDir"
cd "$prg.AppDir"

echo -e "\nextract $file_prg ..."
printf "$file_prg\t["
tar -xzf "$cwd/$file_prg" --checkpoint=500 --checkpoint-action=exec='printf ='
echo -e "]\n"

cp "Discord/discord.png" ./Discord.png


####################################

appimage_name="Discord"
comment="Internet Messenger"
categories="Network;"

####################################


echo "[Desktop Entry]
Name=$appimage_name
GenericName=$appimage_name
Comment=$comment
Exec=$prg
Icon=$prg
Type=Application
Terminal=false
Categories=$categories" > "$prg.desktop"

echo "#!/bin/bash

cd \$APPDIR
desktopfile=~/.local/share/applications/$prg.desktop
iconfile=~/.local/share/pixmaps/$prg.png
autostart=~/.config/autostart/$prg.desktop

test ! -e \"\$desktopfile\" && cp $prg.desktop ~/.local/share/applications/
test ! -e \"\$iconfile\" && cp $prg.png ~/.local/share/pixmaps/
test ! -e \"\$autostart\" && cp $prg.desktop ~/.config/autostart/

if ! grep -q \"\$APPIMAGE\" \"\$desktopfile\"; then
    sed -i \"s:Exec=.*:Exec=\$APPIMAGE:\" \"\$desktopfile\"
    sed -i \"s:Icon=.*:Icon=\$iconfile:\" \"\$desktopfile\"
    sed -i \"s:Exec=.*:Exec=\$APPIMAGE:\" \"\$autostart\"
    sed -i \"s:Icon=.*:Icon=\$iconfile:\" \"\$autostart\"
    /usr/bin/update-desktop-database -q || true
    test -e usr/share/icons/hicolor/icon-theme.cache && {
        test -x /usr/bin/gtk-update-icon-cache && /usr/bin/gtk-update-icon-cache ~/.local/share/pixmaps/ 2>&1 >&- || true
    }
fi

cd \$APPDIR/$prg
./$prg" > AppRun

chmod +x AppRun
cd ..

printf "\n"; for ((i=0; i<$COLUMNS; i++)); { printf '─'; }; echo -e "\n"

env ARCH=$arch ./appimagetool-x86_64.AppImage "$prg.AppDir"
mv "${appimage_name// /_}-$arch.AppImage" "$prg-$VERSION-$arch.AppImage" || true

printf "\n"; for ((i=0; i<$COLUMNS; i++)); { printf '─'; }; echo -e "\n"

rm -rf "$prg.AppDir"
cd ..

echo "appimage saved in $destdir/$prg-$VERSION-$arch.AppImage"
exit 0
